import type { Claim } from "@/types";

export const claims: Claim[] = [
  {
    id: "clm-001",
    policyId: "pol-004",
    clientName: "Apex Media Studios",
    claimType: "Copyright infringement",
    incurredAmount: 45_000,
    paidAmount: 38_000,
    reserveAmount: 7_000,
    dateReported: "2024-09-12",
    status: "closed",
  },
  {
    id: "clm-002",
    policyId: "pol-001",
    clientName: "Pulse Music Group",
    claimType: "AI content – likeness",
    incurredAmount: 12_000,
    paidAmount: 0,
    reserveAmount: 12_000,
    dateReported: "2025-01-20",
    status: "open",
  },
  {
    id: "clm-003",
    policyId: "pol-002",
    clientName: "Canvas Creative Agency",
    claimType: "Stock image misuse",
    incurredAmount: 8_500,
    paidAmount: 8_500,
    reserveAmount: 0,
    dateReported: "2024-11-05",
    status: "closed",
  },
  {
    id: "clm-004",
    policyId: "pol-004",
    clientName: "Apex Media Studios",
    claimType: "Deepfake – defamation",
    incurredAmount: 120_000,
    paidAmount: 25_000,
    reserveAmount: 95_000,
    dateReported: "2024-07-18",
    status: "reserved",
  },
  {
    id: "clm-005",
    policyId: "pol-003",
    clientName: "Nova Games Ltd",
    claimType: "Music sync – clearance",
    incurredAmount: 22_000,
    paidAmount: 22_000,
    reserveAmount: 0,
    dateReported: "2024-10-01",
    status: "closed",
  },
];
