import type { Client } from "@/types";

export const clients: Client[] = [
  {
    id: "cl-001",
    name: "Apex Media Studios",
    industry: "Film",
    contactName: "Sarah Chen",
    contactEmail: "s.chen@apexmedia.co.uk",
    territory: "UK",
    riskGrade: "A",
    activePolicies: 2,
    totalLimit: 2_500_000,
    gwp: 187_500,
    renewalDate: "2025-06-15",
    brokerHandler: "James Walsh",
    totalAssets: 12_000_000,
    aiAssetPercentage: 35,
    portfolioMix: [
      { type: "AI-Assisted", percentage: 40 },
      { type: "Pure Human", percentage: 35 },
      { type: "Hybrid", percentage: 25 },
    ],
  },
  {
    id: "cl-002",
    name: "Nova Games Ltd",
    industry: "Gaming",
    contactName: "Marcus Webb",
    contactEmail: "m.webb@novagames.com",
    territory: "EU",
    riskGrade: "B",
    activePolicies: 1,
    totalLimit: 1_000_000,
    gwp: 72_000,
    renewalDate: "2025-09-01",
    brokerHandler: "Elena Vasquez",
    totalAssets: 5_000_000,
    aiAssetPercentage: 60,
    portfolioMix: [
      { type: "AI-Generated", percentage: 30 },
      { type: "Hybrid", percentage: 45 },
      { type: "AI-Assisted", percentage: 25 },
    ],
  },
  {
    id: "cl-003",
    name: "Pulse Music Group",
    industry: "Music",
    contactName: "David Okonkwo",
    contactEmail: "d.okonkwo@pulsemusic.com",
    territory: "UK",
    riskGrade: "A",
    activePolicies: 3,
    totalLimit: 3_000_000,
    gwp: 225_000,
    renewalDate: "2025-03-20",
    brokerHandler: "James Walsh",
    totalAssets: 8_000_000,
    aiAssetPercentage: 25,
    portfolioMix: [
      { type: "Pure Human", percentage: 50 },
      { type: "AI-Assisted", percentage: 35 },
      { type: "Hybrid", percentage: 15 },
    ],
  },
  {
    id: "cl-004",
    name: "Stride Fashion Co",
    industry: "Fashion",
    contactName: "Emma Laurent",
    contactEmail: "e.laurent@stridefashion.fr",
    territory: "EU",
    riskGrade: "C",
    activePolicies: 1,
    totalLimit: 500_000,
    gwp: 38_000,
    renewalDate: "2025-11-10",
    brokerHandler: "Elena Vasquez",
    totalAssets: 2_500_000,
    aiAssetPercentage: 45,
    portfolioMix: [
      { type: "Hybrid", percentage: 50 },
      { type: "AI-Generated", percentage: 25 },
      { type: "AI-Assisted", percentage: 25 },
    ],
  },
  {
    id: "cl-005",
    name: "Velocity Sports Media",
    industry: "Sports",
    contactName: "Rachel Kim",
    contactEmail: "r.kim@velocitysports.com",
    territory: "US",
    riskGrade: "B",
    activePolicies: 2,
    totalLimit: 1_500_000,
    gwp: 95_000,
    renewalDate: "2025-07-05",
    brokerHandler: "Michael Torres",
    totalAssets: 6_000_000,
    aiAssetPercentage: 20,
    portfolioMix: [
      { type: "Pure Human", percentage: 60 },
      { type: "AI-Assisted", percentage: 40 },
    ],
  },
  {
    id: "cl-006",
    name: "Lumina Advertising",
    industry: "Advertising",
    contactName: "Tom Fletcher",
    contactEmail: "t.fletcher@lumina-ad.com",
    territory: "UK",
    riskGrade: "B",
    activePolicies: 1,
    totalLimit: 750_000,
    gwp: 52_000,
    renewalDate: "2025-08-22",
    brokerHandler: "James Walsh",
    totalAssets: 3_000_000,
    aiAssetPercentage: 55,
    portfolioMix: [
      { type: "AI-Assisted", percentage: 45 },
      { type: "Hybrid", percentage: 35 },
      { type: "AI-Generated", percentage: 20 },
    ],
  },
  {
    id: "cl-007",
    name: "Horizon Pictures",
    industry: "Film",
    contactName: "Anna Bergström",
    contactEmail: "a.bergstrom@horizonpics.se",
    territory: "EU",
    riskGrade: "A",
    activePolicies: 2,
    totalLimit: 2_000_000,
    gwp: 148_000,
    renewalDate: "2025-04-12",
    brokerHandler: "Elena Vasquez",
    totalAssets: 15_000_000,
    aiAssetPercentage: 30,
    portfolioMix: [
      { type: "AI-Assisted", percentage: 40 },
      { type: "Pure Human", percentage: 40 },
      { type: "Hybrid", percentage: 20 },
    ],
  },
  {
    id: "cl-008",
    name: "Echo Records",
    industry: "Music",
    contactName: "Jake Morrison",
    contactEmail: "j.morrison@echorecords.com",
    territory: "US",
    riskGrade: "C",
    activePolicies: 1,
    totalLimit: 400_000,
    gwp: 28_000,
    renewalDate: "2025-10-01",
    brokerHandler: "Michael Torres",
    totalAssets: 1_800_000,
    aiAssetPercentage: 50,
    portfolioMix: [
      { type: "Hybrid", percentage: 45 },
      { type: "AI-Generated", percentage: 30 },
      { type: "AI-Assisted", percentage: 25 },
    ],
  },
  {
    id: "cl-009",
    name: "Pixel Forge Games",
    industry: "Gaming",
    contactName: "Yuki Tanaka",
    contactEmail: "y.tanaka@pixelforge.jp",
    territory: "APAC",
    riskGrade: "B",
    activePolicies: 1,
    totalLimit: 800_000,
    gwp: 58_000,
    renewalDate: "2025-12-15",
    brokerHandler: "Priya Sharma",
    totalAssets: 4_000_000,
    aiAssetPercentage: 70,
    portfolioMix: [
      { type: "AI-Generated", percentage: 40 },
      { type: "Hybrid", percentage: 40 },
      { type: "AI-Assisted", percentage: 20 },
    ],
  },
  {
    id: "cl-010",
    name: "Canvas Creative Agency",
    industry: "Advertising",
    contactName: "Lisa Park",
    contactEmail: "l.park@canvascreative.com",
    territory: "US",
    riskGrade: "A",
    activePolicies: 2,
    totalLimit: 1_200_000,
    gwp: 82_000,
    renewalDate: "2025-05-30",
    brokerHandler: "Michael Torres",
    totalAssets: 5_500_000,
    aiAssetPercentage: 40,
    portfolioMix: [
      { type: "AI-Assisted", percentage: 50 },
      { type: "Hybrid", percentage: 30 },
      { type: "Pure Human", percentage: 20 },
    ],
  },
  {
    id: "cl-011",
    name: "Summit Sports Network",
    industry: "Sports",
    contactName: "Chris Adams",
    contactEmail: "c.adams@summitsports.com",
    territory: "UK",
    riskGrade: "A",
    activePolicies: 2,
    totalLimit: 1_800_000,
    gwp: 125_000,
    renewalDate: "2025-02-28",
    brokerHandler: "James Walsh",
    totalAssets: 9_000_000,
    aiAssetPercentage: 15,
    portfolioMix: [
      { type: "Pure Human", percentage: 70 },
      { type: "AI-Assisted", percentage: 30 },
    ],
  },
  {
    id: "cl-012",
    name: "Verve Fashion House",
    industry: "Fashion",
    contactName: "Sophie Müller",
    contactEmail: "s.muller@vervefashion.de",
    territory: "EU",
    riskGrade: "D",
    activePolicies: 1,
    totalLimit: 250_000,
    gwp: 22_000,
    renewalDate: "2025-11-25",
    brokerHandler: "Elena Vasquez",
    totalAssets: 1_200_000,
    aiAssetPercentage: 65,
    portfolioMix: [
      { type: "AI-Generated", percentage: 45 },
      { type: "Hybrid", percentage: 35 },
      { type: "AI-Assisted", percentage: 20 },
    ],
  },
];
