import type { Quote } from "@/types";

const SYNDICATES = [
  { name: "Beazley", id: "2623" },
  { name: "Hiscox", id: "33" },
  { name: "Brit", id: "2987" },
  { name: "Chaucer", id: "1084" },
  { name: "Tokio Marine Kiln", id: "510" },
  { name: "Canopius", id: "4444" },
] as const;

export const quotes: Quote[] = [
  {
    id: "q-001",
    submissionId: "sub-001",
    syndicateName: "Beazley (2623)",
    syndicateId: "2623",
    leadOrFollow: "lead",
    lineSize: 60,
    premiumQuoted: 67_500,
    deductible: 25_000,
    keyExclusions: ["Pre-2022 training data", "Unlicensed model output"],
    subjectivities: ["Full underwriting information", "Tool inventory"],
    expiryDate: "2025-02-28",
    status: "pending",
  },
  {
    id: "q-002",
    submissionId: "sub-001",
    syndicateName: "Hiscox (33)",
    syndicateId: "33",
    leadOrFollow: "follow",
    lineSize: 40,
    premiumQuoted: 45_000,
    deductible: 50_000,
    keyExclusions: ["Deepfake outside scope", "NILP carve-back"],
    subjectivities: ["Audit of AI workflows"],
    expiryDate: "2025-03-05",
    status: "pending",
  },
  {
    id: "q-003",
    submissionId: "sub-002",
    syndicateName: "Brit (2987)",
    syndicateId: "2987",
    leadOrFollow: "lead",
    lineSize: 100,
    premiumQuoted: 72_000,
    deductible: 75_000,
    keyExclusions: ["Open-source model IP"],
    subjectivities: ["Model disclosure list", "Content policy"],
    expiryDate: "2025-02-15",
    status: "pending",
  },
  {
    id: "q-004",
    submissionId: "sub-005",
    syndicateName: "Hiscox (33)",
    syndicateId: "33",
    leadOrFollow: "lead",
    lineSize: 50,
    premiumQuoted: 42_500,
    deductible: 30_000,
    keyExclusions: ["Sports personality deepfake"],
    subjectivities: ["Rights clearance evidence"],
    expiryDate: "2025-03-01",
    status: "pending",
  },
  {
    id: "q-005",
    submissionId: "sub-005",
    syndicateName: "Canopius (4444)",
    syndicateId: "4444",
    leadOrFollow: "follow",
    lineSize: 50,
    premiumQuoted: 44_000,
    deductible: 40_000,
    keyExclusions: ["US state law variations"],
    subjectivities: ["Territory schedule"],
    expiryDate: "2025-02-25",
    status: "pending",
  },
  {
    id: "q-006",
    submissionId: "sub-006",
    syndicateName: "Beazley (2623)",
    syndicateId: "2623",
    leadOrFollow: "lead",
    lineSize: 100,
    premiumQuoted: 52_000,
    deductible: 50_000,
    keyExclusions: ["Political advertising"],
    subjectivities: ["Client content guidelines"],
    expiryDate: "2025-02-20",
    status: "pending",
  },
  {
    id: "q-007",
    submissionId: "sub-009",
    syndicateName: "Tokio Marine Kiln (510)",
    syndicateId: "510",
    leadOrFollow: "lead",
    lineSize: 55,
    premiumQuoted: 31_900,
    deductible: 80_000,
    keyExclusions: ["APAC regulatory exclusions"],
    subjectivities: ["Local law opinion"],
    expiryDate: "2025-02-18",
    status: "pending",
  },
  {
    id: "q-008",
    submissionId: "sub-009",
    syndicateName: "Canopius (4444)",
    syndicateId: "4444",
    leadOrFollow: "follow",
    lineSize: 45,
    premiumQuoted: 26_100,
    deductible: 100_000,
    keyExclusions: ["Gaming-specific IP"],
    subjectivities: ["Platform T&Cs"],
    expiryDate: "2025-02-22",
    status: "pending",
  },
  {
    id: "q-009",
    submissionId: "sub-012",
    syndicateName: "Chaucer (1084)",
    syndicateId: "1084",
    leadOrFollow: "lead",
    lineSize: 40,
    premiumQuoted: 50_000,
    deductible: 100_000,
    keyExclusions: ["Live sports broadcast"],
    subjectivities: ["Production schedule"],
    expiryDate: "2025-02-15",
    status: "pending",
  },
  {
    id: "q-010",
    submissionId: "sub-012",
    syndicateName: "Hiscox (33)",
    syndicateId: "33",
    leadOrFollow: "follow",
    lineSize: 35,
    premiumQuoted: 43_750,
    deductible: 150_000,
    keyExclusions: ["Pre-existing claims"],
    subjectivities: ["Claims history letter"],
    expiryDate: "2025-02-20",
    status: "pending",
  },
  {
    id: "q-011",
    submissionId: "sub-012",
    syndicateName: "Beazley (2623)",
    syndicateId: "2623",
    leadOrFollow: "follow",
    lineSize: 25,
    premiumQuoted: 31_250,
    deductible: 120_000,
    keyExclusions: ["Social media UGC"],
    subjectivities: ["Risk management statement"],
    expiryDate: "2025-02-25",
    status: "pending",
  },
  {
    id: "q-012",
    submissionId: "sub-015",
    syndicateName: "Canopius (4444)",
    syndicateId: "4444",
    leadOrFollow: "lead",
    lineSize: 100,
    premiumQuoted: 22_000,
    deductible: 25_000,
    keyExclusions: ["Celebrity likeness"],
    subjectivities: ["Design process doc"],
    expiryDate: "2025-02-12",
    status: "pending",
  },
  {
    id: "q-013",
    submissionId: "sub-020",
    syndicateName: "Beazley (2623)",
    syndicateId: "2623",
    leadOrFollow: "lead",
    lineSize: 50,
    premiumQuoted: 34_000,
    deductible: 60_000,
    keyExclusions: ["Archive content"],
    subjectivities: ["Content inventory"],
    expiryDate: "2025-02-14",
    status: "pending",
  },
  {
    id: "q-014",
    submissionId: "sub-020",
    syndicateName: "Brit (2987)",
    syndicateId: "2987",
    leadOrFollow: "follow",
    lineSize: 50,
    premiumQuoted: 34_000,
    deductible: 75_000,
    keyExclusions: ["Music sampling"],
    subjectivities: ["Licence schedule"],
    expiryDate: "2025-02-18",
    status: "pending",
  },
  {
    id: "q-015",
    submissionId: "sub-003",
    syndicateName: "Chaucer (1084)",
    syndicateId: "1084",
    leadOrFollow: "lead",
    lineSize: 60,
    premiumQuoted: 40_800,
    deductible: 50_000,
    keyExclusions: ["Orphan works"],
    subjectivities: ["Copyright register"],
    expiryDate: "2024-12-15",
    status: "accepted",
  },
  {
    id: "q-016",
    submissionId: "sub-003",
    syndicateName: "Tokio Marine Kiln (510)",
    syndicateId: "510",
    leadOrFollow: "follow",
    lineSize: 40,
    premiumQuoted: 27_200,
    deductible: 75_000,
    keyExclusions: ["Mechanical rights"],
    subjectivities: ["Publisher agreements"],
    expiryDate: "2024-12-10",
    status: "accepted",
  },
  {
    id: "q-017",
    submissionId: "sub-010",
    syndicateName: "Hiscox (33)",
    syndicateId: "33",
    leadOrFollow: "lead",
    lineSize: 100,
    premiumQuoted: 42_000,
    deductible: 40_000,
    keyExclusions: ["Stock library claims"],
    subjectivities: ["Agency contract"],
    expiryDate: "2024-12-05",
    status: "accepted",
  },
  {
    id: "q-018",
    submissionId: "sub-007",
    syndicateName: "Brit (2987)",
    syndicateId: "2987",
    leadOrFollow: "lead",
    lineSize: 100,
    premiumQuoted: 0,
    deductible: 0,
    keyExclusions: ["NILP outside appetite"],
    subjectivities: [],
    expiryDate: "2024-12-20",
    status: "declined",
  },
  {
    id: "q-019",
    submissionId: "sub-016",
    syndicateName: "Beazley (2623)",
    syndicateId: "2623",
    leadOrFollow: "lead",
    lineSize: 55,
    premiumQuoted: 60_500,
    deductible: 80_000,
    keyExclusions: ["Co-production carve-back"],
    subjectivities: ["Co-pro agreement"],
    expiryDate: "2025-02-25",
    status: "pending",
  },
  {
    id: "q-020",
    submissionId: "sub-016",
    syndicateName: "Chaucer (1084)",
    syndicateId: "1084",
    leadOrFollow: "follow",
    lineSize: 45,
    premiumQuoted: 49_500,
    deductible: 100_000,
    keyExclusions: ["Documentary footage"],
    subjectivities: ["E&O schedule"],
    expiryDate: "2025-03-01",
    status: "pending",
  },
  {
    id: "q-021",
    submissionId: "sub-011",
    syndicateName: "Beazley (2623)",
    syndicateId: "2623",
    leadOrFollow: "lead",
    lineSize: 50,
    premiumQuoted: 37_500,
    deductible: 50_000,
    keyExclusions: ["Synthetic voice only"],
    subjectivities: ["Deepfake policy"],
    expiryDate: "2025-02-28",
    status: "pending",
  },
  {
    id: "q-022",
    submissionId: "sub-011",
    syndicateName: "Brit (2987)",
    syndicateId: "2987",
    leadOrFollow: "follow",
    lineSize: 50,
    premiumQuoted: 37_500,
    deductible: 60_000,
    keyExclusions: ["Political deepfake"],
    subjectivities: ["Consent documentation"],
    expiryDate: "2025-03-05",
    status: "pending",
  },
  {
    id: "q-023",
    submissionId: "sub-017",
    syndicateName: "Brit (2987)",
    syndicateId: "2987",
    leadOrFollow: "lead",
    lineSize: 60,
    premiumQuoted: 33_000,
    deductible: 100_000,
    keyExclusions: ["User-generated content"],
    subjectivities: ["Platform terms"],
    expiryDate: "2024-11-01",
    status: "accepted",
  },
  {
    id: "q-024",
    submissionId: "sub-017",
    syndicateName: "Hiscox (33)",
    syndicateId: "33",
    leadOrFollow: "follow",
    lineSize: 40,
    premiumQuoted: 22_000,
    deductible: 125_000,
    keyExclusions: ["Music sync"],
    subjectivities: ["Sync licence log"],
    expiryDate: "2024-10-25",
    status: "accepted",
  },
  {
    id: "q-025",
    submissionId: "sub-008",
    syndicateName: "Chaucer (1084)",
    syndicateId: "1084",
    leadOrFollow: "lead",
    lineSize: 50,
    premiumQuoted: 75_000,
    deductible: 100_000,
    keyExclusions: ["Catalog re-release"],
    subjectivities: ["Back catalog list"],
    expiryDate: "2025-02-20",
    status: "pending",
  },
  {
    id: "q-026",
    submissionId: "sub-014",
    syndicateName: "Tokio Marine Kiln (510)",
    syndicateId: "510",
    leadOrFollow: "lead",
    lineSize: 100,
    premiumQuoted: 32_000,
    deductible: 50_000,
    keyExclusions: ["NILP territorial limits"],
    subjectivities: ["Territory schedule"],
    expiryDate: "2025-02-15",
    status: "pending",
  },
  {
    id: "q-027",
    submissionId: "sub-019",
    syndicateName: "Tokio Marine Kiln (510)",
    syndicateId: "510",
    leadOrFollow: "lead",
    lineSize: 100,
    premiumQuoted: 48_000,
    deductible: 90_000,
    keyExclusions: ["APAC likeness laws"],
    subjectivities: ["Talent release forms"],
    expiryDate: "2025-02-18",
    status: "pending",
  },
  {
    id: "q-028",
    submissionId: "sub-008",
    syndicateName: "Hiscox (33)",
    syndicateId: "33",
    leadOrFollow: "follow",
    lineSize: 50,
    premiumQuoted: 75_000,
    deductible: 120_000,
    keyExclusions: ["Sample clearance"],
    subjectivities: ["Sample log"],
    expiryDate: "2025-02-22",
    status: "pending",
  },
  {
    id: "q-029",
    submissionId: "sub-008",
    syndicateName: "Beazley (2623)",
    syndicateId: "2623",
    leadOrFollow: "follow",
    lineSize: 0,
    premiumQuoted: 0,
    deductible: 0,
    keyExclusions: [],
    subjectivities: ["Full submission pending"],
    expiryDate: "2025-03-01",
    status: "pending",
  },
  {
    id: "q-030",
    submissionId: "sub-016",
    syndicateName: "Tokio Marine Kiln (510)",
    syndicateId: "510",
    leadOrFollow: "follow",
    lineSize: 0,
    premiumQuoted: 0,
    deductible: 0,
    keyExclusions: [],
    subjectivities: ["Awaiting lead terms"],
    expiryDate: "2025-03-10",
    status: "pending",
  },
];
