import type { Submission } from "@/types";

export const submissions: Submission[] = [
  {
    id: "sub-001",
    clientId: "cl-001",
    clientName: "Apex Media Studios",
    coverageType: "comprehensive",
    limitRequested: 1_500_000,
    premiumIndication: 112_500,
    status: "quoted",
    syndicates: ["Beazley (2623)", "Hiscox (33)"],
    dateSubmitted: "2025-01-15",
    daysOpen: 26,
    riskGrade: "A",
    territory: "UK",
  },
  {
    id: "sub-002",
    clientId: "cl-002",
    clientName: "Nova Games Ltd",
    coverageType: "ai_content_ip",
    limitRequested: 1_000_000,
    premiumIndication: 72_000,
    status: "submitted",
    syndicates: ["Brit (2987)"],
    dateSubmitted: "2025-02-01",
    daysOpen: 10,
    riskGrade: "B",
    territory: "EU",
  },
  {
    id: "sub-003",
    clientId: "cl-003",
    clientName: "Pulse Music Group",
    coverageType: "copyright_infringement",
    limitRequested: 1_000_000,
    premiumIndication: 68_000,
    status: "bound",
    syndicates: ["Chaucer (1084)", "Tokio Marine Kiln (510)"],
    dateSubmitted: "2024-11-20",
    daysOpen: 0,
    riskGrade: "A",
    territory: "UK",
  },
  {
    id: "sub-004",
    clientId: "cl-004",
    clientName: "Stride Fashion Co",
    coverageType: "deepfake_liability",
    limitRequested: 500_000,
    premiumIndication: 38_000,
    status: "draft",
    syndicates: [],
    dateSubmitted: "",
    daysOpen: 45,
    riskGrade: "C",
    territory: "EU",
  },
  {
    id: "sub-005",
    clientId: "cl-005",
    clientName: "Velocity Sports Media",
    coverageType: "comprehensive",
    limitRequested: 1_200_000,
    premiumIndication: 85_000,
    status: "quoted",
    syndicates: ["Hiscox (33)", "Canopius (4444)"],
    dateSubmitted: "2025-01-28",
    daysOpen: 13,
    riskGrade: "B",
    territory: "US",
  },
  {
    id: "sub-006",
    clientId: "cl-006",
    clientName: "Lumina Advertising",
    coverageType: "ai_content_ip",
    limitRequested: 750_000,
    premiumIndication: 52_000,
    status: "submitted",
    syndicates: ["Beazley (2623)"],
    dateSubmitted: "2025-02-05",
    daysOpen: 6,
    riskGrade: "B",
    territory: "UK",
  },
  {
    id: "sub-007",
    clientId: "cl-007",
    clientName: "Horizon Pictures",
    coverageType: "nilp_protection",
    limitRequested: 1_000_000,
    premiumIndication: 62_000,
    status: "declined",
    syndicates: ["Brit (2987)"],
    dateSubmitted: "2024-12-10",
    daysOpen: 63,
    riskGrade: "A",
    territory: "EU",
  },
  {
    id: "sub-008",
    clientId: "cl-003",
    clientName: "Pulse Music Group",
    coverageType: "comprehensive",
    limitRequested: 2_000_000,
    premiumIndication: 150_000,
    status: "submitted",
    syndicates: ["Chaucer (1084)"],
    dateSubmitted: "2025-02-08",
    daysOpen: 3,
    riskGrade: "A",
    territory: "UK",
  },
  {
    id: "sub-009",
    clientId: "cl-009",
    clientName: "Pixel Forge Games",
    coverageType: "ai_content_ip",
    limitRequested: 800_000,
    premiumIndication: 58_000,
    status: "quoted",
    syndicates: ["Tokio Marine Kiln (510)", "Canopius (4444)"],
    dateSubmitted: "2025-01-20",
    daysOpen: 21,
    riskGrade: "B",
    territory: "APAC",
  },
  {
    id: "sub-010",
    clientId: "cl-010",
    clientName: "Canvas Creative Agency",
    coverageType: "copyright_infringement",
    limitRequested: 600_000,
    premiumIndication: 42_000,
    status: "bound",
    syndicates: ["Hiscox (33)"],
    dateSubmitted: "2024-12-01",
    daysOpen: 0,
    riskGrade: "A",
    territory: "US",
  },
  {
    id: "sub-011",
    clientId: "cl-001",
    clientName: "Apex Media Studios",
    coverageType: "deepfake_liability",
    limitRequested: 1_000_000,
    premiumIndication: 75_000,
    status: "submitted",
    syndicates: ["Beazley (2623)", "Brit (2987)"],
    dateSubmitted: "2025-02-01",
    daysOpen: 10,
    riskGrade: "A",
    territory: "UK",
  },
  {
    id: "sub-012",
    clientId: "cl-011",
    clientName: "Summit Sports Network",
    coverageType: "comprehensive",
    limitRequested: 1_800_000,
    premiumIndication: 125_000,
    status: "quoted",
    syndicates: ["Chaucer (1084)", "Hiscox (33)", "Beazley (2623)"],
    dateSubmitted: "2025-01-10",
    daysOpen: 31,
    riskGrade: "A",
    territory: "UK",
  },
  {
    id: "sub-013",
    clientId: "cl-008",
    clientName: "Echo Records",
    coverageType: "ai_content_ip",
    limitRequested: 400_000,
    premiumIndication: 28_000,
    status: "draft",
    syndicates: [],
    dateSubmitted: "",
    daysOpen: 18,
    riskGrade: "C",
    territory: "US",
  },
  {
    id: "sub-014",
    clientId: "cl-005",
    clientName: "Velocity Sports Media",
    coverageType: "nilp_protection",
    limitRequested: 500_000,
    premiumIndication: 32_000,
    status: "submitted",
    syndicates: ["Tokio Marine Kiln (510)"],
    dateSubmitted: "2025-02-06",
    daysOpen: 5,
    riskGrade: "B",
    territory: "US",
  },
  {
    id: "sub-015",
    clientId: "cl-012",
    clientName: "Verve Fashion House",
    coverageType: "deepfake_liability",
    limitRequested: 250_000,
    premiumIndication: 22_000,
    status: "quoted",
    syndicates: ["Canopius (4444)"],
    dateSubmitted: "2025-01-25",
    daysOpen: 16,
    riskGrade: "D",
    territory: "EU",
  },
  {
    id: "sub-016",
    clientId: "cl-007",
    clientName: "Horizon Pictures",
    coverageType: "comprehensive",
    limitRequested: 1_500_000,
    premiumIndication: 110_000,
    status: "submitted",
    syndicates: ["Beazley (2623)", "Chaucer (1084)"],
    dateSubmitted: "2025-02-03",
    daysOpen: 8,
    riskGrade: "A",
    territory: "EU",
  },
  {
    id: "sub-017",
    clientId: "cl-002",
    clientName: "Nova Games Ltd",
    coverageType: "copyright_infringement",
    limitRequested: 800_000,
    premiumIndication: 55_000,
    status: "bound",
    syndicates: ["Brit (2987)", "Hiscox (33)"],
    dateSubmitted: "2024-10-15",
    daysOpen: 0,
    riskGrade: "B",
    territory: "EU",
  },
  {
    id: "sub-018",
    clientId: "cl-006",
    clientName: "Lumina Advertising",
    coverageType: "comprehensive",
    limitRequested: 500_000,
    premiumIndication: 35_000,
    status: "expired",
    syndicates: ["Canopius (4444)"],
    dateSubmitted: "2024-08-01",
    daysOpen: 194,
    riskGrade: "B",
    territory: "UK",
  },
  {
    id: "sub-019",
    clientId: "cl-009",
    clientName: "Pixel Forge Games",
    coverageType: "deepfake_liability",
    limitRequested: 600_000,
    premiumIndication: 48_000,
    status: "submitted",
    syndicates: ["Tokio Marine Kiln (510)"],
    dateSubmitted: "2025-02-07",
    daysOpen: 4,
    riskGrade: "B",
    territory: "APAC",
  },
  {
    id: "sub-020",
    clientId: "cl-011",
    clientName: "Summit Sports Network",
    coverageType: "ai_content_ip",
    limitRequested: 1_000_000,
    premiumIndication: 68_000,
    status: "quoted",
    syndicates: ["Beazley (2623)", "Brit (2987)"],
    dateSubmitted: "2025-01-18",
    daysOpen: 23,
    riskGrade: "A",
    territory: "UK",
  },
];
