import type { Wording } from "@/types";

export const wordings: Wording[] = [
  {
    id: "w-001",
    name: "AI Content IP – Standard Form",
    version: "2.1",
    status: "approved",
    coverageType: "ai_content_ip",
    lastModified: "2025-01-15",
    author: "James Walsh",
    syndicateRequirements: ["Beazley: Appendix A", "Hiscox: Schedule 2"],
    endorsements: ["AI Tool Schedule", "Territory Limitation"],
  },
  {
    id: "w-002",
    name: "Deepfake Liability – Core Wording",
    version: "1.3",
    status: "approved",
    coverageType: "deepfake_liability",
    lastModified: "2024-11-20",
    author: "Elena Vasquez",
    syndicateRequirements: ["Brit: Consent warranty", "Chaucer: NIL carve-back"],
    endorsements: ["Consent Documentation", "Likeness Schedule"],
  },
  {
    id: "w-003",
    name: "Copyright Infringement – Standard",
    version: "3.0",
    status: "approved",
    coverageType: "copyright_infringement",
    lastModified: "2024-10-01",
    author: "James Walsh",
    syndicateRequirements: ["All: Orphan works exclusion"],
    endorsements: ["Mechanical Rights", "Sync Licence Schedule"],
  },
  {
    id: "w-004",
    name: "NILP Protection – Draft",
    version: "0.9",
    status: "under_review",
    coverageType: "nilp_protection",
    lastModified: "2025-02-01",
    author: "Michael Torres",
    syndicateRequirements: ["TBC"],
    endorsements: ["Territorial Limits", "Regulatory Exclusion"],
  },
  {
    id: "w-005",
    name: "Comprehensive AI E&O",
    version: "1.2",
    status: "approved",
    coverageType: "comprehensive",
    lastModified: "2024-12-10",
    author: "Elena Vasquez",
    syndicateRequirements: ["Beazley: Full form", "Hiscox: Addendum 1", "Chaucer: Section 4"],
    endorsements: ["AI Tool Exclusions", "NILP Carve-back", "Territory Schedule"],
  },
  {
    id: "w-006",
    name: "AI Tool Exclusions – Library",
    version: "1.0",
    status: "approved",
    coverageType: "ai_content_ip",
    lastModified: "2024-09-15",
    author: "Priya Sharma",
    syndicateRequirements: [],
    endorsements: ["Midjourney", "DALL-E", "Suno", "Runway", "Stable Diffusion"],
  },
  {
    id: "w-007",
    name: "Territorial Limits – EU/US",
    version: "2.0",
    status: "approved",
    coverageType: "comprehensive",
    lastModified: "2025-01-05",
    author: "Michael Torres",
    syndicateRequirements: ["EU AI Act compliance clause", "US state law schedule"],
    endorsements: ["EU Annex", "US State Schedule"],
  },
  {
    id: "w-008",
    name: "Pre-2022 Training Data Exclusion",
    version: "1.1",
    status: "superseded",
    coverageType: "ai_content_ip",
    lastModified: "2024-06-01",
    author: "James Walsh",
    syndicateRequirements: [],
    endorsements: [],
  },
];
